# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - CHN
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:18:08
# Country: CHN
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:18:08",
    "country_code": "CHN",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "standard",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR CHN
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for CHN.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.CHN.CHN_meta_data import CHN_meta_data
#   
#   country_name = CHN_meta_data['name']
#   gdp_data = CHN_meta_data.get('wb_gdp_capita', {})
#   population = CHN_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

CHN_meta_data = {
    "iso3Code": "CHN",
    "iso2Code": "CN",
    "name": "China",
    "region": "East Asia & Pacific",
    "adminregion": "East Asia & Pacific (excluding high income)",
    "incomeLevel": "Upper middle income",
    "lendingType": "IBRD",
    "capitalCity": "Beijing",
    "longitude": 116.286,
    "latitude": 40.0495,
    "countryName": "China",
    "officialStateName": "The People's Republic of China",
    "sovereignty": "UN member state",
    "alpha2Code": "CN",
    "alpha3Code": "CHN",
    "numericCode": "156",
    "subdivisionCode": "ISO 3166-2:CN",
    "ccTLD": ".cn",
    "internetCode": ".cn",
    "population": 1412175000,
    "surfaceArea": 9562910,
    "landArea": 9388210,
    "neighbors": [
        "MNG",
        "RUS",
        "KAZ",
        "KGZ",
        "TJK",
        "AFG",
        "PAK",
        "IND",
        "MMR",
        "LAO",
        "VNM",
        "HKG",
        "MAC",
        "TWN",
        "PRK"
    ],
    "CHN": {
        "currencyCode": "CNY",
        "currencyName": "Chinese Yuan",
        "currencySymbol": "¥"
    },
    "officialLanguages": [
        "Mandarin"
    ],
    "gdp": 17963170521079.8,
    "gdpPerCapita": 12720.2156397612,
    "gdpPpp": 30327320296268.4,
    "gdpPppPerCapita": 21475.610527214,
    "ciCountryName": "china",
    "ciIso2Code": "CN",
    "callingCodes": [
        "86"
    ],
    "ciCurrencies": [
        "CNY"
    ],
    "ciLanguages": [
        "zh"
    ],
    "timezones": [
        "UTC+08:00"
    ],
    "tld": [
        ".cn"
    ],
    "ciLatlng": [
        35,
        105
    ],
    "ciLatitude": 35,
    "ciLongitude": 105,
    "ciCapital": "Beijing",
    "capitalLatitude": 39.906217,
    "capitalLongitude": 116.391276,
    "ciBorders": [
        "AFG",
        "BTN",
        "MMR",
        "HKG",
        "IND",
        "KAZ",
        "PRK",
        "KGZ",
        "LAO",
        "MAC",
        "MNG",
        "PAK",
        "RUS",
        "TJK",
        "VNM"
    ],
    "provinces": [
        "Anhui",
        "Beijing",
        "Chongqing",
        "Fujian",
        "Gansu",
        "Guangdong",
        "Guangxi",
        "Guizhou",
        "Hainan",
        "Hebei",
        "Heilongjiang",
        "Henan",
        "Hubei",
        "Hunan",
        "Jiangsu",
        "Jiangxi",
        "Jilin",
        "Liaoning",
        "Nei Mongol",
        "Ningxia",
        "Qinghai",
        "Shaanxi",
        "Shandong",
        "Shanghai",
        "Shanxi",
        "Sichuan",
        "Tianjin",
        "Xinjiang",
        "Xizang (Tibet)",
        "Yunnan",
        "Zhejiang"
    ],
    "demonym": "Chinese",
    "ciRegion": "Asia",
    "subregion": "Eastern Asia",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 5,
        "fields_already_populated": 39,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 88.64,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "CHN",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:18:08.245855",
        "topic_update_mode": "standard",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:18:08.251857"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "CHN"

def get_country_name():
    """Get the country name."""
    return CHN_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return CHN_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in CHN_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(CHN_meta_data)
    topics = get_all_topics()
    retrieval_meta = CHN_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - CHN - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
