# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - TLS
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:33
# Country: TLS
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:33",
    "country_code": "TLS",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR TLS
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for TLS.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.TLS.TLS_meta_data import TLS_meta_data
#   
#   country_name = TLS_meta_data['name']
#   gdp_data = TLS_meta_data.get('wb_gdp_capita', {})
#   population = TLS_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

TLS_meta_data = {
    "iso3Code": "TLS",
    "iso2Code": "TL",
    "name": "Timor-Leste",
    "region": "East Asia & Pacific",
    "adminregion": "East Asia & Pacific (excluding high income)",
    "incomeLevel": "Lower middle income",
    "lendingType": "Blend",
    "capitalCity": "Dili",
    "longitude": 125.567,
    "latitude": -8.56667,
    "countryName": "Timor-Leste [ab]",
    "officialStateName": "The Democratic Republic of Timor-Leste",
    "sovereignty": "UN member state",
    "alpha2Code": "TL",
    "alpha3Code": "TLS",
    "numericCode": "626",
    "subdivisionCode": "ISO 3166-2:TL",
    "ccTLD": ".tl",
    "internetCode": ".tl",
    "population": 1341296,
    "surfaceArea": 14870,
    "landArea": 14870,
    "neighbors": [
        "IDN"
    ],
    "TLS": {
        "currencyName": "United States Dollar",
        "currencySymbol": "$",
        "currencyCode": "USD"
    },
    "officialLanguages": [
        "Portuguese",
        "Tetum"
    ],
    "gdp": 3163324631.03158,
    "gdpPerCapita": 2358.4090544008,
    "gdpPpp": 6476213640.09336,
    "gdpPppPerCapita": 4828.32547036102,
    "ciCountryName": "east timor",
    "ciIso2Code": "TL",
    "callingCodes": [
        "670"
    ],
    "ciCurrencies": [
        "USD"
    ],
    "ciLanguages": [
        "pt"
    ],
    "timezones": [
        "UTC+09:00"
    ],
    "tld": [
        ".tl"
    ],
    "ciLatlng": [
        -8.83333333,
        125.91666666
    ],
    "ciLatitude": -8.83333333,
    "ciLongitude": 125.91666666,
    "ciCapital": "Dili",
    "capitalLatitude": 28.651718,
    "capitalLongitude": 77.221939,
    "ciBorders": [
        "IDN"
    ],
    "provinces": [
        "Tobago"
    ],
    "demonym": "East Timorese",
    "ciRegion": "Asia",
    "subregion": "South-Eastern Asia",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 5,
        "fields_already_populated": 39,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 88.64,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "TLS",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:33.041249",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:33.045249"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "TLS"

def get_country_name():
    """Get the country name."""
    return TLS_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return TLS_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in TLS_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(TLS_meta_data)
    topics = get_all_topics()
    retrieval_meta = TLS_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - TLS - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
