# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - URY
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:33
# Country: URY
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:33",
    "country_code": "URY",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR URY
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for URY.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.URY.URY_meta_data import URY_meta_data
#   
#   country_name = URY_meta_data['name']
#   gdp_data = URY_meta_data.get('wb_gdp_capita', {})
#   population = URY_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

URY_meta_data = {
    "iso3Code": "URY",
    "iso2Code": "UY",
    "name": "Uruguay",
    "region": "Latin America & Caribbean",
    "adminregion": "",
    "incomeLevel": "High income",
    "lendingType": "IBRD",
    "capitalCity": "Montevideo",
    "longitude": -56.0675,
    "latitude": -34.8941,
    "countryName": "Uruguay",
    "officialStateName": "The Oriental Republic of Uruguay",
    "sovereignty": "UN member state",
    "alpha2Code": "UY",
    "alpha3Code": "URY",
    "numericCode": "858",
    "subdivisionCode": "ISO 3166-2:UY",
    "ccTLD": ".uy",
    "internetCode": ".uy",
    "population": 3422794,
    "surfaceArea": 176220,
    "landArea": 175020,
    "neighbors": [
        "BRA",
        "ARG"
    ],
    "URY": {
        "currencyName": "Uruguayan Peso",
        "currencySymbol": "$U",
        "currencyCode": "UYU"
    },
    "officialLanguages": [
        "Spanish"
    ],
    "gdp": 71177146197.4951,
    "gdpPerCapita": 20795.0423535553,
    "gdpPpp": 98720175602.8539,
    "gdpPppPerCapita": 28841.9857002361,
    "ciCountryName": "uruguay",
    "ciIso2Code": "UY",
    "callingCodes": [
        "598"
    ],
    "ciCurrencies": [
        "UYI",
        "UYU"
    ],
    "ciLanguages": [
        "es"
    ],
    "timezones": [
        "UTC−03:00"
    ],
    "tld": [
        ".uy"
    ],
    "ciLatlng": [
        -33,
        -56
    ],
    "ciLatitude": -33,
    "ciLongitude": -56,
    "ciCapital": "Montevideo",
    "capitalLatitude": -34.905904,
    "capitalLongitude": -56.191357,
    "ciBorders": [
        "ARG",
        "BRA"
    ],
    "provinces": [
        "Artigas",
        "Canelones",
        "Cerro Largo",
        "Colonia",
        "Durazno",
        "Flores",
        "Florida",
        "Lavalleja",
        "Maldonado",
        "Montevideo",
        "Paysandu",
        "Rio Negro",
        "Rivera",
        "Rocha",
        "Salto",
        "San Jose",
        "Soriano",
        "Tacuarembo",
        "Treinta y Tres"
    ],
    "demonym": "Uruguayan",
    "ciRegion": "Americas",
    "subregion": "South America",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 5,
        "fields_already_populated": 39,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 88.64,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "URY",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:33.283074",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:33.287077"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "URY"

def get_country_name():
    """Get the country name."""
    return URY_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return URY_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in URY_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(URY_meta_data)
    topics = get_all_topics()
    retrieval_meta = URY_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - URY - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
