# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - WSM
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:33
# Country: WSM
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:33",
    "country_code": "WSM",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR WSM
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for WSM.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.WSM.WSM_meta_data import WSM_meta_data
#   
#   country_name = WSM_meta_data['name']
#   gdp_data = WSM_meta_data.get('wb_gdp_capita', {})
#   population = WSM_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

WSM_meta_data = {
    "iso3Code": "WSM",
    "iso2Code": "WS",
    "name": "Samoa",
    "region": "East Asia & Pacific",
    "adminregion": "East Asia & Pacific (excluding high income)",
    "incomeLevel": "Lower middle income",
    "lendingType": "IDA",
    "capitalCity": "Apia",
    "longitude": -171.752,
    "latitude": -13.8314,
    "countryName": "Samoa",
    "officialStateName": "The Independent State of Samoa",
    "sovereignty": "UN member state",
    "alpha2Code": "WS",
    "alpha3Code": "WSM",
    "numericCode": "882",
    "subdivisionCode": "ISO 3166-2:WS",
    "ccTLD": ".ws",
    "internetCode": ".ws",
    "population": 222382,
    "surfaceArea": 2840,
    "landArea": 2780,
    "neighbors": [],
    "WSM": {
        "currencyName": "Samoan Tala",
        "currencySymbol": "T",
        "currencyCode": "WST"
    },
    "officialLanguages": [
        "Samoan",
        "English"
    ],
    "gdp": 832421565.372356,
    "gdpPerCapita": 3743.20567929219,
    "gdpPpp": 1343444500.68468,
    "gdpPppPerCapita": 6041.15666144148,
    "ciCountryName": "samoa",
    "ciIso2Code": "WS",
    "callingCodes": [
        "685"
    ],
    "ciCurrencies": [
        "WST"
    ],
    "ciLanguages": [
        "sm",
        "en"
    ],
    "timezones": [
        "UTC+13:00"
    ],
    "tld": [
        ".ws"
    ],
    "ciLatlng": [
        -13.58333333,
        -172.33333333
    ],
    "ciLatitude": -13.58333333,
    "ciLongitude": -172.33333333,
    "ciCapital": "Apia",
    "capitalLatitude": -13.834369,
    "capitalLongitude": -171.769279,
    "ciBorders": [],
    "provinces": [
        "A'ana",
        "Aiga-i-le-Tai",
        "Atua",
        "Fa'asaleleaga",
        "Gaga'emauga",
        "Gagaifomauga",
        "Palauli",
        "Satupa'itea",
        "Tuamasaga",
        "Va'a-o-Fonoti",
        "Vaisigano"
    ],
    "demonym": "Samoan",
    "ciRegion": "Oceania",
    "subregion": "Polynesia",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 5,
        "fields_already_populated": 39,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 88.64,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "WSM",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:33.529074",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:33.546075"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "WSM"

def get_country_name():
    """Get the country name."""
    return WSM_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return WSM_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in WSM_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(WSM_meta_data)
    topics = get_all_topics()
    retrieval_meta = WSM_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - WSM - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
