# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - GIB
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:29
# Country: GIB
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:29",
    "country_code": "GIB",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR GIB
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for GIB.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.GIB.GIB_meta_data import GIB_meta_data
#   
#   country_name = GIB_meta_data['name']
#   gdp_data = GIB_meta_data.get('wb_gdp_capita', {})
#   population = GIB_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

GIB_meta_data = {
    "iso3Code": "GIB",
    "iso2Code": "GI",
    "name": "Gibraltar",
    "region": "Europe & Central Asia",
    "adminregion": "",
    "incomeLevel": "High income",
    "lendingType": "Not classified",
    "capitalCity": "",
    "longitude": "",
    "latitude": "",
    "countryName": "Gibraltar",
    "officialStateName": "Gibraltar",
    "sovereignty": "United Kingdom",
    "alpha2Code": "GI",
    "alpha3Code": "GIB",
    "numericCode": "292",
    "subdivisionCode": "ISO 3166-2:GI",
    "ccTLD": ".gi",
    "internetCode": ".gi",
    "population": 32649,
    "surfaceArea": 10,
    "landArea": 10,
    "neighbors": [],
    "GIB": {
        "currencyCode": "GIP",
        "currencyName": "Gibraltar pound",
        "currencySymbol": "£"
    },
    "officialLanguages": [
        "English"
    ],
    "gdp": 0.0,
    "gdpPerCapita": 0.0,
    "gdpPpp": 0.0,
    "gdpPppPerCapita": 0.0,
    "ciCountryName": "gibraltar",
    "ciIso2Code": "GI",
    "callingCodes": [
        "350"
    ],
    "ciCurrencies": [
        "GIP"
    ],
    "ciLanguages": [
        "en"
    ],
    "timezones": [],
    "tld": [
        ".gi"
    ],
    "ciLatlng": [
        36.13333333,
        -5.35
    ],
    "ciLatitude": 36.13333333,
    "ciLongitude": -5.35,
    "ciCapital": "Gibraltar",
    "capitalLatitude": 36.140807,
    "capitalLongitude": -5.35413,
    "ciBorders": [
        "ESP"
    ],
    "provinces": [
        "Gibraltar"
    ],
    "demonym": "Gibraltar",
    "ciRegion": "Europe",
    "subregion": "Southern Europe",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 9,
        "fields_already_populated": 35,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 79.55,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "GIB",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:29.730322",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:29.735838"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "GIB"

def get_country_name():
    """Get the country name."""
    return GIB_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return GIB_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in GIB_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(GIB_meta_data)
    topics = get_all_topics()
    retrieval_meta = GIB_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - GIB - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
