# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - MAR
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:31
# Country: MAR
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:31",
    "country_code": "MAR",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR MAR
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for MAR.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.MAR.MAR_meta_data import MAR_meta_data
#   
#   country_name = MAR_meta_data['name']
#   gdp_data = MAR_meta_data.get('wb_gdp_capita', {})
#   population = MAR_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

MAR_meta_data = {
    "iso3Code": "MAR",
    "iso2Code": "MA",
    "name": "Morocco",
    "region": "Middle East & North Africa",
    "adminregion": "Middle East & North Africa (excluding high income)",
    "incomeLevel": "Lower middle income",
    "lendingType": "IBRD",
    "capitalCity": "Rabat",
    "longitude": -6.8704,
    "latitude": 33.9905,
    "countryName": "Morocco",
    "officialStateName": "The Kingdom of Morocco",
    "sovereignty": "UN member state",
    "alpha2Code": "MA",
    "alpha3Code": "MAR",
    "numericCode": "504",
    "subdivisionCode": "ISO 3166-2:MA",
    "ccTLD": ".ma",
    "internetCode": ".ma",
    "population": 37457971,
    "surfaceArea": 446550,
    "landArea": 446300,
    "neighbors": [
        "ESH",
        "DZA"
    ],
    "MAR": {
        "currencyName": "Moroccan dirham",
        "currencySymbol": "د.م.",
        "currencyCode": "MAD"
    },
    "officialLanguages": [
        "Arabic",
        "Amazigh",
        "French"
    ],
    "gdp": 134181587769.796,
    "gdpPerCapita": 3527.94189453125,
    "gdpPpp": 362034055671.668,
    "gdpPppPerCapita": 9518.7060546875,
    "ciCountryName": "morocco",
    "ciIso2Code": "MA",
    "callingCodes": [
        "212"
    ],
    "ciCurrencies": [
        "MAD"
    ],
    "ciLanguages": [
        "ar"
    ],
    "timezones": [
        "UTC"
    ],
    "tld": [
        ".ma"
    ],
    "ciLatlng": [
        32,
        -5
    ],
    "ciLatitude": 32,
    "ciLongitude": -5,
    "ciCapital": "Rabat",
    "capitalLatitude": 34.022405,
    "capitalLongitude": -6.834543,
    "ciBorders": [
        "DZA",
        "ESH",
        "ESP"
    ],
    "provinces": [
        "Agadir",
        "Al Hoceima",
        "Azilal",
        "Ben Slimane",
        "Beni Mellal",
        "Boulemane",
        "Casablanca",
        "Chaouen",
        "El Jadida",
        "El Kelaa des Srarhna",
        "Er Rachidia",
        "Essaouira",
        "Fes",
        "Figuig",
        "Guelmim",
        "Ifrane",
        "Kenitra",
        "Khemisset",
        "Khenifra",
        "Khouribga",
        "Laayoune",
        "Larache",
        "Marrakech",
        "Meknes",
        "Nador",
        "Ouarzazate",
        "Oujda",
        "Rabat-Sale",
        "Safi",
        "Settat",
        "Sidi Kacem",
        "Tan-Tan",
        "Tanger",
        "Taounate",
        "Taroudannt",
        "Tata",
        "Taza",
        "Tetouan",
        "Tiznit"
    ],
    "demonym": "Moroccan",
    "ciRegion": "Africa",
    "subregion": "Northern Africa",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 5,
        "fields_already_populated": 39,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 88.64,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "MAR",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:31.092477",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:31.095476"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "MAR"

def get_country_name():
    """Get the country name."""
    return MAR_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return MAR_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in MAR_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(MAR_meta_data)
    topics = get_all_topics()
    retrieval_meta = MAR_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - MAR - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
