# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - MKD
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:31
# Country: MKD
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:31",
    "country_code": "MKD",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR MKD
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for MKD.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.MKD.MKD_meta_data import MKD_meta_data
#   
#   country_name = MKD_meta_data['name']
#   gdp_data = MKD_meta_data.get('wb_gdp_capita', {})
#   population = MKD_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

MKD_meta_data = {
    "iso3Code": "MKD",
    "iso2Code": "MK",
    "name": "North Macedonia",
    "region": "Europe & Central Asia",
    "adminregion": "Europe & Central Asia (excluding high income)",
    "incomeLevel": "Upper middle income",
    "lendingType": "IBRD",
    "capitalCity": "Skopje",
    "longitude": 21.4361,
    "latitude": 42.0024,
    "countryName": "North Macedonia",
    "officialStateName": "The Republic of North Macedonia[12]",
    "sovereignty": "UN member state",
    "alpha2Code": "MK",
    "alpha3Code": "MKD",
    "numericCode": "807",
    "subdivisionCode": "ISO 3166-2:MK",
    "ccTLD": ".mk",
    "internetCode": ".mk",
    "population": 2057679,
    "surfaceArea": 25710,
    "landArea": 25220,
    "neighbors": [
        "ALB",
        "SRB",
        "BGR",
        "GRC"
    ],
    "MKD": {
        "currencyName": "Macedonian Denar",
        "currencySymbol": "ден",
        "currencyCode": "MKD"
    },
    "officialLanguages": [
        "Macedonian"
    ],
    "gdp": 13563132057.2486,
    "gdpPerCapita": 6591.4712922903,
    "gdpPpp": 41486411449.9479,
    "gdpPppPerCapita": 20161.7509096161,
    "ciCountryName": "republic of macedonia",
    "ciIso2Code": "MK",
    "callingCodes": [
        "389"
    ],
    "ciCurrencies": [
        "MKD"
    ],
    "ciLanguages": [
        "mk"
    ],
    "timezones": [
        "UTC+01:00"
    ],
    "tld": [
        ".mk"
    ],
    "ciLatlng": [
        41.83333333,
        22
    ],
    "ciLatitude": 41.83333333,
    "ciLongitude": 22,
    "ciCapital": "Skopje",
    "capitalLatitude": 41.996092,
    "capitalLongitude": 21.43165,
    "ciBorders": [
        "ALB",
        "BGR",
        "GRC",
        "KOS",
        "SRB"
    ],
    "provinces": [
        "Aracinovo",
        "Bac",
        "Belcista",
        "Berovo",
        "Bistrica",
        "Bitola",
        "Blatec",
        "Bogdanci",
        "Bogomila",
        "Bogovinje",
        "Bosilovo",
        "Brvenica",
        "Cair (Skopje)",
        "Capari",
        "Caska",
        "Cegrane",
        "Centar (Skopje)",
        "Centar Zupa",
        "Cesinovo",
        "Cucer-Sandevo",
        "Debar",
        "Delcevo",
        "Delogozdi",
        "Demir Hisar",
        "Demir Kapija",
        "Dobrusevo",
        "Dolna Banjica",
        "Dolneni",
        "Dorce Petrov (Skopje)",
        "Drugovo",
        "Dzepciste",
        "Gazi Baba (Skopje)",
        "Gevgelija",
        "Gostivar",
        "Gradsko",
        "Ilinden",
        "Izvor",
        "Jegunovce",
        "Kamenjane",
        "Karbinci",
        "Karpos (Skopje)",
        "Kavadarci",
        "Kicevo",
        "Kisela Voda (Skopje)",
        "Klecevce",
        "Kocani",
        "Konce",
        "Kondovo",
        "Konopiste",
        "Kosel",
        "Kratovo",
        "Kriva Palanka",
        "Krivogastani",
        "Krusevo",
        "Kuklis",
        "Kukurecani",
        "Kumanovo",
        "Labunista",
        "Lipkovo",
        "Lozovo",
        "Lukovo",
        "Makedonska Kamenica",
        "Makedonski Brod",
        "Mavrovi Anovi",
        "Meseista",
        "Miravci",
        "Mogila",
        "Murtino",
        "Negotino",
        "Negotino-Poloska",
        "Novaci",
        "Novo Selo",
        "Oblesevo",
        "Ohrid",
        "Orasac",
        "Orizari",
        "Oslomej",
        "Pehcevo",
        "Petrovec",
        "Plasnia",
        "Podares",
        "Prilep",
        "Probistip",
        "Radovis",
        "Rankovce",
        "Resen",
        "Rosoman",
        "Rostusa",
        "Samokov",
        "Saraj",
        "Sipkovica",
        "Sopiste",
        "Sopotnika",
        "Srbinovo",
        "Star Dojran",
        "Staravina",
        "Staro Nagoricane",
        "Stip",
        "Struga",
        "Strumica",
        "Studenicani",
        "Suto Orizari (Skopje)",
        "Sveti Nikole",
        "Tearce",
        "Tetovo",
        "Topolcani",
        "Valandovo",
        "Vasilevo",
        "Veles",
        "Velesta",
        "Vevcani",
        "Vinica",
        "Vitoliste",
        "Vranestica",
        "Vrapciste",
        "Vratnica",
        "Vrutok",
        "Zajas",
        "Zelenikovo",
        "Zileno",
        "Zitose",
        "Zletovo",
        "Zrnovci"
    ],
    "demonym": "Macedonian",
    "ciRegion": "Europe",
    "subregion": "Southern Europe",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 5,
        "fields_already_populated": 39,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 88.64,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "MKD",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:31.264162",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:31.269160"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "MKD"

def get_country_name():
    """Get the country name."""
    return MKD_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return MKD_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in MKD_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(MKD_meta_data)
    topics = get_all_topics()
    retrieval_meta = MKD_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - MKD - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
