# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - PRI
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:32
# Country: PRI
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:32",
    "country_code": "PRI",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR PRI
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for PRI.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.PRI.PRI_meta_data import PRI_meta_data
#   
#   country_name = PRI_meta_data['name']
#   gdp_data = PRI_meta_data.get('wb_gdp_capita', {})
#   population = PRI_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

PRI_meta_data = {
    "iso3Code": "PRI",
    "iso2Code": "PR",
    "name": "Puerto Rico",
    "region": "Latin America & Caribbean",
    "adminregion": "",
    "incomeLevel": "High income",
    "lendingType": "Not classified",
    "capitalCity": "San Juan",
    "longitude": -66.0,
    "latitude": 18.23,
    "countryName": "Puerto Rico",
    "officialStateName": "The Commonwealth of Puerto Rico",
    "sovereignty": "United States",
    "alpha2Code": "PR",
    "alpha3Code": "PRI",
    "numericCode": "630",
    "subdivisionCode": "ISO 3166-2:PR",
    "ccTLD": ".pr",
    "internetCode": ".pr",
    "population": 3221789,
    "surfaceArea": 8870,
    "landArea": 8870,
    "neighbors": [],
    "PRI": {
        "currencyName": "United States Dollar",
        "currencySymbol": "$",
        "currencyCode": "USD"
    },
    "officialLanguages": [
        "Spanish",
        "English"
    ],
    "gdp": 113434800000,
    "gdpPerCapita": 35208.6371888414,
    "gdpPpp": 130474647576.048,
    "gdpPppPerCapita": 40497.5768357418,
    "ciCountryName": "puerto rico",
    "ciIso2Code": "PR",
    "callingCodes": [
        "1787",
        "1939"
    ],
    "ciCurrencies": [
        "USD"
    ],
    "ciLanguages": [
        "es",
        "en"
    ],
    "timezones": [],
    "tld": [
        ".pr"
    ],
    "ciLatlng": [
        18.25,
        -66.5
    ],
    "ciLatitude": 18.25,
    "ciLongitude": -66.5,
    "ciCapital": "San Juan",
    "capitalLatitude": 18.465299,
    "capitalLongitude": -66.116666,
    "ciBorders": [],
    "provinces": [
        "Adjuntas",
        "Aguada",
        "Aguadilla",
        "Aguas Buenas",
        "Aibonito",
        "Anasco",
        "Arecibo",
        "Arroyo",
        "Barceloneta",
        "Barranquitas",
        "Bayamon",
        "Cabo Rojo",
        "Caguas",
        "Camuy",
        "Canovanas",
        "Carolina",
        "Catano",
        "Cayey",
        "Ceiba",
        "Ciales",
        "Cidra",
        "Coamo",
        "Comerio",
        "Corozal",
        "Culebra",
        "Dorado",
        "Fajardo",
        "Florida",
        "Guanica",
        "Guayama",
        "Guayanilla",
        "Guaynabo",
        "Gurabo",
        "Hatillo",
        "Hormigueros",
        "Humacao",
        "Isabela",
        "Jayuya",
        "Juana Diaz",
        "Juncos",
        "Lajas",
        "Lares",
        "Las Marias",
        "Las Piedras",
        "Loiza",
        "Luquillo",
        "Manati",
        "Maricao",
        "Maunabo",
        "Mayaguez",
        "Moca",
        "Morovis",
        "Naguabo",
        "Naranjito",
        "Orocovis",
        "Patillas",
        "Penuelas",
        "Ponce",
        "Quebradillas",
        "Rincon",
        "Rio Grande",
        "Sabana Grande",
        "Salinas",
        "San German",
        "San Juan",
        "San Lorenzo",
        "San Sebastian",
        "Santa Isabel",
        "Toa Alta",
        "Toa Baja",
        "Trujillo Alto",
        "Utuado",
        "Vega Alta",
        "Vega Baja",
        "Vieques",
        "Villalba",
        "Yabucoa",
        "Yauco"
    ],
    "demonym": "Puerto Rican",
    "ciRegion": "Americas",
    "subregion": "Caribbean",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 5,
        "fields_already_populated": 39,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 88.64,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "PRI",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:32.036686",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:32.041686"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "PRI"

def get_country_name():
    """Get the country name."""
    return PRI_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return PRI_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in PRI_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(PRI_meta_data)
    topics = get_all_topics()
    retrieval_meta = PRI_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - PRI - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
