# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - PHL
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:31
# Country: PHL
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:31",
    "country_code": "PHL",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR PHL
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for PHL.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.PHL.PHL_meta_data import PHL_meta_data
#   
#   country_name = PHL_meta_data['name']
#   gdp_data = PHL_meta_data.get('wb_gdp_capita', {})
#   population = PHL_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

PHL_meta_data = {
    "iso3Code": "PHL",
    "iso2Code": "PH",
    "name": "Philippines",
    "region": "East Asia & Pacific",
    "adminregion": "East Asia & Pacific (excluding high income)",
    "incomeLevel": "Lower middle income",
    "lendingType": "IBRD",
    "capitalCity": "Manila",
    "longitude": 121.035,
    "latitude": 14.5515,
    "countryName": "Philippines (the)",
    "officialStateName": "The Republic of the Philippines",
    "sovereignty": "UN member state",
    "alpha2Code": "PH",
    "alpha3Code": "PHL",
    "numericCode": "608",
    "subdivisionCode": "ISO 3166-2:PH",
    "ccTLD": ".ph",
    "internetCode": ".ph",
    "population": 115559009,
    "surfaceArea": 300000,
    "landArea": 298170,
    "neighbors": [
        "MYS",
        "IDN"
    ],
    "PHL": {
        "currencyName": "Philippine Peso",
        "currencySymbol": "₱",
        "currencyCode": "PHP"
    },
    "officialLanguages": [
        "Filipino",
        "English"
    ],
    "gdp": 404284327311.713,
    "gdpPerCapita": 3498.50981598253,
    "gdpPpp": 1170982075549.65,
    "gdpPppPerCapita": 10133.1958943127,
    "ciCountryName": "philippines",
    "ciIso2Code": "PH",
    "callingCodes": [
        "63"
    ],
    "ciCurrencies": [
        "PHP"
    ],
    "ciLanguages": [
        "en"
    ],
    "timezones": [
        "UTC+08:00"
    ],
    "tld": [
        ".ph"
    ],
    "ciLatlng": [
        13,
        122
    ],
    "ciLatitude": 13,
    "ciLongitude": 122,
    "ciCapital": "Manila",
    "capitalLatitude": 14.590622,
    "capitalLongitude": 120.97997,
    "ciBorders": [],
    "provinces": [
        "Abra",
        "Agusan del Norte",
        "Agusan del Sur",
        "Aklan",
        "Albay",
        "Angeles",
        "Antique",
        "Aurora",
        "Bacolod",
        "Bago",
        "Baguio",
        "Bais",
        "Basilan",
        "Basilan City",
        "Bataan",
        "Batanes",
        "Batangas",
        "Batangas City",
        "Benguet",
        "Bohol",
        "Bukidnon",
        "Bulacan",
        "Butuan",
        "Cabanatuan",
        "Cadiz",
        "Cagayan",
        "Cagayan de Oro",
        "Calbayog",
        "Caloocan",
        "Camarines Norte",
        "Camarines Sur",
        "Camiguin",
        "Canlaon",
        "Capiz",
        "Catanduanes",
        "Cavite",
        "Cavite City",
        "Cebu",
        "Cebu City",
        "Cotabato",
        "Dagupan",
        "Danao",
        "Dapitan",
        "Davao City Davao",
        "Davao del Sur",
        "Davao Oriental",
        "Dipolog",
        "Dumaguete",
        "Eastern Samar",
        "General Santos",
        "Gingoog",
        "Ifugao",
        "Iligan",
        "Ilocos Norte",
        "Ilocos Sur",
        "Iloilo",
        "Iloilo City",
        "Iriga",
        "Isabela",
        "Kalinga-Apayao",
        "La Carlota",
        "La Union",
        "Laguna",
        "Lanao del Norte",
        "Lanao del Sur",
        "Laoag",
        "Lapu-Lapu",
        "Legaspi",
        "Leyte",
        "Lipa",
        "Lucena",
        "Maguindanao",
        "Mandaue",
        "Manila",
        "Marawi",
        "Marinduque",
        "Masbate",
        "Mindoro Occidental",
        "Mindoro Oriental",
        "Misamis Occidental",
        "Misamis Oriental",
        "Mountain",
        "Naga",
        "Negros Occidental",
        "Negros Oriental",
        "North Cotabato",
        "Northern Samar",
        "Nueva Ecija",
        "Nueva Vizcaya",
        "Olongapo",
        "Ormoc",
        "Oroquieta",
        "Ozamis",
        "Pagadian",
        "Palawan",
        "Palayan",
        "Pampanga",
        "Pangasinan",
        "Pasay",
        "Puerto Princesa",
        "Quezon",
        "Quezon City",
        "Quirino",
        "Rizal",
        "Romblon",
        "Roxas",
        "Samar",
        "San Carlos (in Negros Occidental)",
        "San Carlos (in Pangasinan)",
        "San Jose",
        "San Pablo",
        "Silay",
        "Siquijor",
        "Sorsogon",
        "South Cotabato",
        "Southern Leyte",
        "Sultan Kudarat",
        "Sulu",
        "Surigao",
        "Surigao del Norte",
        "Surigao del Sur",
        "Tacloban",
        "Tagaytay",
        "Tagbilaran",
        "Tangub",
        "Tarlac",
        "Tawitawi",
        "Toledo",
        "Trece Martires",
        "Zambales",
        "Zamboanga",
        "Zamboanga del Norte",
        "Zamboanga del Sur"
    ],
    "demonym": "Filipino",
    "ciRegion": "Asia",
    "subregion": "South-Eastern Asia",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 5,
        "fields_already_populated": 39,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 88.64,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "PHL",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:31.923687",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:31.927685"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "PHL"

def get_country_name():
    """Get the country name."""
    return PHL_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return PHL_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in PHL_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(PHL_meta_data)
    topics = get_all_topics()
    retrieval_meta = PHL_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - PHL - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
