# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - PER
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:31
# Country: PER
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:31",
    "country_code": "PER",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR PER
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for PER.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.PER.PER_meta_data import PER_meta_data
#   
#   country_name = PER_meta_data['name']
#   gdp_data = PER_meta_data.get('wb_gdp_capita', {})
#   population = PER_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

PER_meta_data = {
    "iso3Code": "PER",
    "iso2Code": "PE",
    "name": "Peru",
    "region": "Latin America & Caribbean",
    "adminregion": "Latin America & Caribbean (excluding high income)",
    "incomeLevel": "Upper middle income",
    "lendingType": "IBRD",
    "capitalCity": "Lima",
    "longitude": -77.0465,
    "latitude": -12.0931,
    "countryName": "Peru",
    "officialStateName": "The Republic of PerÃº",
    "sovereignty": "UN member state",
    "alpha2Code": "PE",
    "alpha3Code": "PER",
    "numericCode": "604",
    "subdivisionCode": "ISO 3166-2:PE",
    "ccTLD": ".pe",
    "internetCode": ".pe",
    "population": 34049588,
    "surfaceArea": 1285220,
    "landArea": 1280000,
    "neighbors": [
        "ECU",
        "COL",
        "BRA",
        "CHL",
        "BOL"
    ],
    "PER": {
        "currencyName": "Peruvian Nuevo Sol",
        "currencySymbol": "S/.",
        "currencyCode": "PEN"
    },
    "officialLanguages": [
        "Spanish",
        "Quechua",
        "Aymara"
    ],
    "gdp": 242631549613.268,
    "gdpPerCapita": 7125.8292350929,
    "gdpPpp": 512361799463.736,
    "gdpPppPerCapita": 15047.5183272037,
    "ciCountryName": "peru",
    "ciIso2Code": "PE",
    "callingCodes": [
        "51"
    ],
    "ciCurrencies": [
        "PEN"
    ],
    "ciLanguages": [
        "es"
    ],
    "timezones": [
        "UTC−05:00"
    ],
    "tld": [
        ".pe"
    ],
    "ciLatlng": [
        -10,
        -76
    ],
    "ciLatitude": -10,
    "ciLongitude": -76,
    "ciCapital": "Lima",
    "capitalLatitude": -12.062106,
    "capitalLongitude": -77.036526,
    "ciBorders": [
        "BOL",
        "BRA",
        "CHL",
        "COL",
        "ECU"
    ],
    "provinces": [
        "Amazonas",
        "Ancash",
        "Apurimac",
        "Arequipa",
        "Ayacucho",
        "Cajamarca",
        "Callao",
        "Cusco",
        "Huancavelica",
        "Huanuco",
        "Ica",
        "Junin",
        "La Libertad",
        "Lambayeque",
        "Lima",
        "Loreto",
        "Madre de Dios",
        "Moquegua",
        "Pasco",
        "Piura",
        "Puno",
        "San Martin",
        "Tacna",
        "Tumbes",
        "Ucayali"
    ],
    "demonym": "Peruvian",
    "ciRegion": "Americas",
    "subregion": "South America",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 5,
        "fields_already_populated": 39,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 88.64,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "PER",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:31.899684",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:31.902683"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "PER"

def get_country_name():
    """Get the country name."""
    return PER_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return PER_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in PER_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(PER_meta_data)
    topics = get_all_topics()
    retrieval_meta = PER_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - PER - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
