# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - POL
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:32
# Country: POL
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:32",
    "country_code": "POL",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR POL
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for POL.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.POL.POL_meta_data import POL_meta_data
#   
#   country_name = POL_meta_data['name']
#   gdp_data = POL_meta_data.get('wb_gdp_capita', {})
#   population = POL_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

POL_meta_data = {
    "iso3Code": "POL",
    "iso2Code": "PL",
    "name": "Poland",
    "region": "Europe & Central Asia",
    "adminregion": "",
    "incomeLevel": "High income",
    "lendingType": "IBRD",
    "capitalCity": "Warsaw",
    "longitude": 21.02,
    "latitude": 52.26,
    "countryName": "Poland",
    "officialStateName": "The Republic of Poland",
    "sovereignty": "UN member state",
    "alpha2Code": "PL",
    "alpha3Code": "POL",
    "numericCode": "616",
    "subdivisionCode": "ISO 3166-2:PL",
    "ccTLD": ".pl",
    "internetCode": ".pl",
    "population": 37561599,
    "surfaceArea": 312710,
    "landArea": 306100,
    "neighbors": [
        "DEU",
        "CZE",
        "SVK",
        "LTU",
        "BLR",
        "UKR"
    ],
    "POL": {
        "currencyName": "Polish złoty",
        "currencySymbol": "zł",
        "currencyCode": "PLN"
    },
    "officialLanguages": [
        "Polish"
    ],
    "gdp": 688176605954.787,
    "gdpPerCapita": 18321.2808899533,
    "gdpPpp": 1625235688246.77,
    "gdpPppPerCapita": 43268.5437126031,
    "ciCountryName": "poland",
    "ciIso2Code": "PL",
    "callingCodes": [
        "48"
    ],
    "ciCurrencies": [
        "PLN"
    ],
    "ciLanguages": [
        "pl"
    ],
    "timezones": [
        "UTC+01:00"
    ],
    "tld": [
        ".pl"
    ],
    "ciLatlng": [
        52,
        20
    ],
    "ciLatitude": 52,
    "ciLongitude": 20,
    "ciCapital": "Warsaw",
    "capitalLatitude": 52.233717,
    "capitalLongitude": 21.071411,
    "ciBorders": [
        "BLR",
        "CZE",
        "DEU",
        "LTU",
        "RUS",
        "SVK",
        "UKR"
    ],
    "provinces": [
        "Dolnoslaskie",
        "Kujawsko-Pomorskie",
        "Lodzkie",
        "Lubelskie",
        "Lubuskie",
        "Malopolskie",
        "Mazowieckie",
        "Opolskie",
        "Podkarpackie",
        "Podlaskie",
        "Pomorskie",
        "Slaskie",
        "Swietokrzyskie",
        "Warminsko-Mazurskie",
        "Wielkopolskie",
        "Zachodniopomorskie"
    ],
    "demonym": "Polish",
    "ciRegion": "Europe",
    "subregion": "Eastern Europe",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 5,
        "fields_already_populated": 39,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 88.64,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "POL",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:32.008686",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:32.014686"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "POL"

def get_country_name():
    """Get the country name."""
    return POL_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return POL_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in POL_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(POL_meta_data)
    topics = get_all_topics()
    retrieval_meta = POL_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - POL - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
