country_name_to_code = {
    'Afghanistan': 'AFG',
    'Africa': 'AFR',
    'Africa Eastern and Southern': 'AFE',
    'Africa Western and Central': 'AFW',
    'Akrotiri Sovereign Base Area': 'WSB',
    'Akrotiri and Dhekelia': 'XAD',
    'Albania': 'ALB',
    'Algeria': 'DZA',
    'American Samoa': 'ASM',
    'Andorra': 'AND',
    'Angola': 'AGO',
    'Anguilla': 'AIA',
    'Antarctica': 'ATA',
    'Antigua and Barbuda': 'ATG',
    'Arab World': 'ARB',
    'Argentina': 'ARG',
    'Armenia': 'ARM',
    'Aruba': 'ABW',
    'Ashmore and Cartier Islands': 'ATC',
    'Australia': 'AUS',
    'Australian Indian Ocean Territories': 'IOA',
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Bahrain': 'BHR',
    'Baikonur': 'KAB',
    'Bajo Nuevo Bank': 'BJN',
    'Bangladesh': 'BGD',
    'Barbados': 'BRB',
    'Belarus': 'BLR',
    'Belgium': 'BEL',
    'Belize': 'BLZ',
    'Benin': 'BEN',
    'Bermuda': 'BMU',
    'Bhutan': 'BTN',
    'Bir Tawil': 'BRT',
    'Bolivia': 'BOL',
    'Bonaire, Sint Eustatius, and Saba': 'BES',
    'Bosnia and Herzegovina': 'BIH',
    'Botswana': 'BWA',
    'Bouvet Island': 'BVT',
    'Brazil': 'BRA',
    'Brazilian Island': 'BRI',
    'British Indian Ocean Territory': 'IOT',
    'British Virgin Islands': 'VGB',
    'Brunei': 'BRN',
    'Bulgaria': 'BGR',
    'Burkina Faso': 'BFA',
    'Burundi': 'BDI',
    'Cambodia': 'KHM',
    'Cameroon': 'CMR',
    'Canada': 'CAN',
    'Cape Verde': 'CPV',
    'Caribbean small states': 'CSS',
    'Caspian Sea': 'XCA',
    'Cayman Islands': 'CYM',
    'Central African Republic': 'CAF',
    'Central Europe and the Baltics': 'CEB',
    'Chad': 'TCD',
    'Channel Islands': 'CHI',
    'Chile': 'CHL',
    'Christmas Island': 'CXR',
    'Clipperton Island': 'XCL',
    'Cocos (Keeling) Islands': 'CCK',
    'Colombia': 'COL',
    'Comoros': 'COM',
    'Cook Islands': 'COK',
    'Coral Sea Islands': 'CSI',
    'Costa Rica': 'CRI',
    'Croatia': 'HRV',
    'Cuba': 'CUB',
    'Curaçao': 'CUW',
    'Cyprus': 'CYP',
    'Czech Republic': 'CZE',
    'Democratic Republic of the Congo': 'COD',
    'Denmark': 'DNK',
    'Dhekelia Cantonment': 'ESB',
    'Djibouti': 'DJI',
    'Dominica': 'DMA',
    'Dominican Republic': 'DOM',
    'Early-demographic dividend': 'EAR',
    'East Asia & Pacific': 'EAS',
    'East Asia & Pacific (International Bank for Reconstruction and Development and International Development Association countries)': 'TEA',
    'East Asia & Pacific (International Bank for Reconstruction and Development)': 'BEA',
    'East Asia & Pacific (International Development Association)': 'DEA',
    'East Asia & Pacific (excluding high income)': 'EAP',
    'East Asia and the Pacific (IFC classification)': 'CEA',
    'East Timor': 'TLS',
    'Ecuador': 'ECU',
    'Egypt': 'EGY',
    'El Salvador': 'SLV',
    'Equatorial Guinea': 'GNQ',
    'Eritrea': 'ERI',
    'Estonia': 'EST',
    'Eswatini': 'SWZ',
    'Ethiopia': 'ETH',
    'Euro area': 'EMU',
    'Europe & Central Asia': 'ECS',
    'Europe & Central Asia (IDA-eligible countries)': 'DEC',
    'Europe & Central Asia (International Bank for Reconstruction and Development and International Development Association countries)': 'TEC',
    'Europe & Central Asia (International Bank for Reconstruction and Development)': 'BEC',
    'Europe & Central Asia (excluding high income)': 'ECA',
    'Europe and Central Asia (IFC classification)': 'CEU',
    'European Union': 'EUU',
    'Falkland Islands': 'FLK',
    'Faroe Islands': 'FRO',
    'Federated States of Micronesia': 'FSM',
    'Fiji': 'FJI',
    'Finland': 'FIN',
    'Fragile and conflict affected situations': 'FCS',
    'France': 'FRA',
    'French Guiana': 'GUF',
    'French Polynesia': 'PYF',
    'French Southern and Antarctic Lands': 'ATF',
    'Gabon': 'GAB',
    'Georgia': 'GEO',
    'Germany': 'DEU',
    'Ghana': 'GHA',
    'Gibraltar': 'GIB',
    'Greece': 'GRC',
    'Greenland': 'GRL',
    'Grenada': 'GRD',
    'Guadeloupe': 'GLP',
    'Guam': 'GUM',
    'Guantanamo Bay Naval Base': 'USG',
    'Guatemala': 'GTM',
    'Guernsey': 'GGY',
    'Guinea': 'GIN',
    'Guinea-Bissau': 'GNB',
    'Guyana': 'GUY',
    'Haiti': 'HTI',
    'Heard Island and McDonald Islands': 'HMD',
    'Heavily indebted poor countries (HIPC)': 'HPC',
    'High income': 'HIC',
    'Honduras': 'HND',
    'Hong Kong': 'HKG',
    'Hungary': 'HUN',
    'IBRD countries classified as high income': 'BHI',
    'IBRD, including blend': 'IBB',
    'IDA countries classified as fragile situations, excluding Sub-Saharan Africa': 'FXS',
    'IDA countries in Sub-Saharan Africa classified as fragile situations': 'DSF',
    'IDA countries in Sub-Saharan Africa not classified as fragile situations': 'DNS',
    'IDA countries not classified as fragile situations, excluding Sub-Saharan Africa': 'NXS',
    'Iceland': 'ISL',
    'India': 'IND',
    'Indonesia': 'IDN',
    'International Bank for Reconstruction and Development and International Development Association total': 'IBT', 'International Bank for Reconstruction and Development, Only': 'IBD',
    'International Development Association blend': 'IDB',
    'International Development Association only': 'IDX',
    'International Development Association total': 'IDA',
    'Iran': 'IRN',
    'Iraq': 'IRQ',
    'Ireland': 'IRL',
    'Isle of Man': 'IMN',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Ivory Coast': 'CIV',
    'Jamaica': 'JAM',
    'Japan': 'JPN',
    'Jersey': 'JEY',
    'Jordan': 'JOR',
    'Kazakhstan': 'KAZ',
    'Kenya': 'KEN',
    'Kiribati': 'KIR',
    'Kosovo': 'XKX',
    'Kuwait': 'KWT',
    'Kyrgyzstan': 'KGZ',
    'Laos': 'LAO',
    'Late-demographic dividend': 'LTE',
    'Latin America & Caribbean': 'LCN',
    'Latin America & Caribbean (excluding high income)': 'LAC',
    'Latin America & the Caribbean (IDA-eligible countries)': 'DLA',
    'Latin America & the Caribbean (International Bank for Reconstruction and Development and International Development Association countries)': 'TLA',
    'Latin America & the Caribbean (International Bank for Reconstruction and Development)': 'BLA',
    'Latin America and the Caribbean (IFC classification)': 'CLA',
    'Latvia': 'LVA',
    'Least developed countries: UN classification': 'LDC',
    'Lebanon': 'LBN',
    'Lesotho': 'LSO',
    'Liberia': 'LBR',
    'Libya': 'LBY',
    'Liechtenstein': 'LIE',
    'Lithuania': 'LTU',
    'Low & middle income': 'LMY',
    'Low income': 'LIC',
    'Lower middle income': 'LMC',
    'Luxembourg': 'LUX',
    'Macau': 'MAC',
    'Madagascar': 'MDG',
    'Malawi': 'MWI',
    'Malaysia': 'MYS',
    'Maldives': 'MDV',
    'Mali': 'MLI',
    'Malta': 'MLT',
    'Marshall Islands': 'MHL',
    'Martinique': 'MTQ',
    'Mauritania': 'MRT',
    'Mauritius': 'MUS',
    'Mayotte': 'MYT',
    'Mexico': 'MEX',
    'Middle East & North Africa': 'MEA',
    'Middle East & North Africa (IDA-eligible countries)': 'DMN',
    'Middle East & North Africa (International Bank for Reconstruction and Development and International Development Association countries)': 'TMN',
    'Middle East & North Africa (International Bank for Reconstruction and Development)': 'BMN',
    'Middle East & North Africa (excluding high income)': 'MNA',
    'Middle East (developing only)': 'MDE',
    'Middle East and North Africa (IFC classification)': 'CME',
    'Middle income': 'MIC',
    'Moldova': 'MDA',
    'Monaco': 'MCO',
    'Mongolia': 'MNG',
    'Montenegro': 'MNE',
    'Montserrat': 'MSR',
    'Morocco': 'MAR',
    'Mozambique': 'MOZ',
    'Myanmar': 'MMR',
    'Namibia': 'NAM',
    'Nauru': 'NRU',
    'Nepal': 'NPL',
    'Netherlands': 'NLD',
    'New Caledonia': 'NCL',
    'New Zealand': 'NZL',
    'Nicaragua': 'NIC',
    'Niger': 'NER',
    'Nigeria': 'NGA',
    'Niue': 'NIU',
    'Non-resource rich Sub-Saharan Africa countries': 'NRS',
    'Norfolk Island': 'NFK',
    'North Africa': 'NAF',
    'North America': 'NAC',
    'North Korea': 'PRK',
    'North Macedonia': 'MKD',
    'Northern Cyprus': 'ZNC',
    'Northern Mariana Islands': 'MNP',
    'Norway': 'NOR',
    'Not classified': 'INX',
    'OECD members': 'OED',
    'Oman': 'OMN',
    'Other small states': 'OSS',
    'Pacific island small states': 'PSS',
    'Pakistan': 'PAK',
    'Palau': 'PLW',
    'Palestine': 'PSE',
    'Panama': 'PAN',
    'Papua New Guinea': 'PNG',
    'Paracel Islands': 'XPI',
    'Paraguay': 'PRY',
    "People's Republic of China": 'CHN',
    'Peru': 'PER',
    'Philippines': 'PHL',
    'Pitcairn Islands': 'PCN',
    'Poland': 'POL',
    'Portugal': 'PRT',
    'Post-demographic dividend': 'PST',
    'Pre-demographic dividend': 'PRE',
    'Puerto Rico': 'PRI',
    'Qatar': 'QAT',
    'Republic of the Congo': 'COG',
    'Resource rich Sub-Saharan Africa countries': 'RRS',
    'Romania': 'ROU',
    'Russia': 'RUS',
    'Rwanda': 'RWA',
    'Réunion': 'REU',
    'Saint Barthélemy': 'BLM',
    'Saint Helena': 'SHN',
    'Saint Kitts and Nevis': 'KNA',
    'Saint Lucia': 'LCA',
    'Saint Martin': 'MAF',
    'Saint Pierre and Miquelon': 'SPM',
    'Saint Vincent and the Grenadines': 'VCT',
    'Samoa': 'WSM',
    'San Marino': 'SMR',
    'Saudi Arabia': 'SAU',
    'Scarborough Shoal': 'SCR',
    'Senegal': 'SEN',
    'Serbia': 'SRB',
    'Serranilla Bank': 'SER',
    'Seychelles': 'SYC',
    'Siachen Glacier': 'KAS',
    'Sierra Leone': 'SLE',
    'Singapore': 'SGP',
    'Sint Maarten': 'SXM',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Small states': 'SST',
    'Solomon Islands': 'SLB',
    'Somalia': 'SOM',
    'Somaliland': 'SOL',
    'South Africa': 'ZAF',
    'South Asia': 'SAS',
    'South Asia (IDA-eligible countries)': 'DSA',
    'South Asia (IFC classification)': 'CSA',
    'South Asia (International Bank for Reconstruction and Development and International Development Association)': 'TSA',
    'South Georgia and the South Sandwich Islands': 'SGS',
    'South Korea': 'KOR',
    'South Sudan': 'SSD',
    'Southern Patagonian Ice Field': 'SPI',
    'Spain': 'ESP',
    'Spratly Islands': 'XSP',
    'Sri Lanka': 'LKA',
    'Sub-Saharan Africa': 'SSF',
    'Sub-Saharan Africa (IDA-eligible countries)': 'DSS',
    'Sub-Saharan Africa (IFC classification)': 'CAA',
    'Sub-Saharan Africa (International Bank for Reconstruction and Development and International Development Association countries)': 'TSS',
    'Sub-Saharan Africa (International Bank for Reconstruction and Development)': 'BSS',
    'Sub-Saharan Africa (excluding high income)': 'SSA',
    'Sub-Saharan Africa excluding South Africa': 'SXZ',
    'Sub-Saharan Africa excluding South Africa and Nigeria': 'XZN',
    'Sudan': 'SDN',
    'Suriname': 'SUR',
    'Svalbard and Jan Mayen': 'SJM',
    'Sweden': 'SWE',
    'Switzerland': 'CHE',
    'Syria': 'SYR',
    'São Tomé and Príncipe': 'STP',
    'Taiwan': 'TWN',
    'Tajikistan': 'TJK',
    'Tanzania': 'TZA',
    'Thailand': 'THA',
    'The Bahamas': 'BHS',
    'The Gambia': 'GMB',
    'Togo': 'TGO',
    'Tokelau': 'TKL',
    'Tonga': 'TON',
    'Trinidad and Tobago': 'TTO',
    'Tunisia': 'TUN',
    'Turkey': 'TUR',
    'Turkish Republic of Northern Cyprus': 'CYN',
    'Turkmenistan': 'TKM',
    'Turks and Caicos Islands': 'TCA',
    'Tuvalu': 'TUV',
    'Uganda': 'UGA',
    'Ukraine': 'UKR',
    'United Arab Emirates': 'ARE',
    'United Kingdom': 'GBR',
    'United Nations Buffer Zone in Cyprus': 'CNM',
    'United States Minor Outlying Islands': 'UMI',
    'United States Virgin Islands': 'VIR',
    'United States of America': 'USA',
    'Upper middle income': 'UMC',
    'Uruguay': 'URY',
    'Uzbekistan': 'UZB',
    'Vanuatu': 'VUT',
    'Vatican City': 'VAT',
    'Venezuela': 'VEN',
    'Vietnam': 'VNM',
    'Wake Island': 'PGA',
    'Wallis and Futuna': 'WLF',
    'Western Sahara': 'ESH',
    'World': 'WLD',
    'Yemen': 'YEM',
    'Zambia': 'ZMB',
    'Zimbabwe': 'ZWE',
    'Åland': 'ALD',
    'Åland Islands': 'ALA'
}
