# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - TWN
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:33
# Country: TWN
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:33",
    "country_code": "TWN",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR TWN
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for TWN.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.TWN.TWN_meta_data import TWN_meta_data
#   
#   country_name = TWN_meta_data['name']
#   gdp_data = TWN_meta_data.get('wb_gdp_capita', {})
#   population = TWN_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

TWN_meta_data = {
    "iso3Code": "TWN",
    "iso2Code": "TW",
    "name": "Taiwan, China",
    "region": "East Asia & Pacific",
    "adminregion": "",
    "incomeLevel": "High income",
    "lendingType": "Not classified",
    "capitalCity": "",
    "longitude": "",
    "latitude": "",
    "countryName": "Taiwan (Province of China)",
    "officialStateName": "The Republic of China",
    "sovereignty": "Disputed [aa]",
    "alpha2Code": "TW",
    "alpha3Code": "TWN",
    "numericCode": "158",
    "subdivisionCode": "ISO 3166-2:TW",
    "ccTLD": ".tw",
    "internetCode": ".tw",
    "neighbors": [],
    "TWN": {
        "currencyName": "New Taiwan Dollar",
        "currencySymbol": "NT$",
        "currencyCode": "TWD"
    },
    "officialLanguages": [
        "Mandarin"
    ],
    "ciCountryName": "taiwan",
    "ciIso2Code": "TW",
    "callingCodes": [
        "886"
    ],
    "ciCurrencies": [
        "TWD"
    ],
    "ciLanguages": [
        "zh"
    ],
    "timezones": [
        "UTC+08:00"
    ],
    "tld": [
        ".tw"
    ],
    "ciLatlng": [
        23.5,
        121
    ],
    "ciLatitude": 23.5,
    "ciLongitude": 121,
    "ciCapital": "Taipei",
    "capitalLatitude": 25.03752,
    "capitalLongitude": 121.56368,
    "ciBorders": [],
    "provinces": [
        "Chang-hua",
        "Chi-lung",
        "Chia-i",
        "Chia-i",
        "Chung-hsing-hsin-ts'un",
        "Hsin-chu",
        "Hsin-chu",
        "Hua-lien",
        "I-lan",
        "Kao-hsiung",
        "Kao-hsiung",
        "Miao-li",
        "Nan-t'ou",
        "P'eng-hu",
        "P'ing-tung",
        "T'ai-chung",
        "T'ai-chung",
        "T'ai-nan",
        "T'ai-nan",
        "T'ai-pei",
        "T'ai-pei",
        "T'ai-tung",
        "T'ao-yuan",
        "Yun-lin"
    ],
    "demonym": "Taiwanese",
    "ciRegion": "Asia",
    "subregion": "Eastern Asia",
    "population": 0,
    "surfaceArea": 0.0,
    "landArea": 0.0,
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "gdp": 0.0,
    "gdpPerCapita": 0.0,
    "gdpPpp": 0.0,
    "gdpPppPerCapita": 0.0,
    "_retrieval_metadata": {
        "default_values_applied": 12,
        "fields_already_populated": 32,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 72.73,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "TWN",
        "sources_attempted": 13,
        "sources_merged": 5,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:33.182348",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:33.186558"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "TWN"

def get_country_name():
    """Get the country name."""
    return TWN_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return TWN_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in TWN_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(TWN_meta_data)
    topics = get_all_topics()
    retrieval_meta = TWN_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - TWN - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
