# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - TUR
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:33
# Country: TUR
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:33",
    "country_code": "TUR",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR TUR
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for TUR.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.TUR.TUR_meta_data import TUR_meta_data
#   
#   country_name = TUR_meta_data['name']
#   gdp_data = TUR_meta_data.get('wb_gdp_capita', {})
#   population = TUR_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

TUR_meta_data = {
    "iso3Code": "TUR",
    "iso2Code": "TR",
    "name": "Turkiye",
    "region": "Europe & Central Asia",
    "adminregion": "Europe & Central Asia (excluding high income)",
    "incomeLevel": "Upper middle income",
    "lendingType": "IBRD",
    "capitalCity": "Ankara",
    "longitude": 32.3606,
    "latitude": 39.7153,
    "countryName": "TÃ¼rkiye [ac]",
    "officialStateName": "The Republic of TÃ¼rkiye",
    "sovereignty": "UN member state",
    "alpha2Code": "TR",
    "alpha3Code": "TUR",
    "numericCode": "792",
    "subdivisionCode": "ISO 3166-2:TR",
    "ccTLD": ".tr",
    "internetCode": ".tr",
    "population": 85341241,
    "surfaceArea": 785350,
    "landArea": 769630,
    "neighbors": [
        "GRC",
        "BGR",
        "GEO",
        "ARM",
        "AZE",
        "IRN",
        "IRQ",
        "SYR"
    ],
    "TUR": {
        "currencyName": "Turkish Lira",
        "currencySymbol": "₺",
        "currencyCode": "TRY"
    },
    "officialLanguages": [
        "Turkish"
    ],
    "gdp": 905987824096.127,
    "gdpPerCapita": 10616.0610448133,
    "gdpPpp": 3180983794231.42,
    "gdpPppPerCapita": 37273.6997606048,
    "ciCountryName": "turkey",
    "ciIso2Code": "TR",
    "callingCodes": [
        "90"
    ],
    "ciCurrencies": [
        "TRY"
    ],
    "ciLanguages": [
        "tr"
    ],
    "timezones": [
        "UTC+02:00"
    ],
    "tld": [
        ".tr"
    ],
    "ciLatlng": [
        39,
        35
    ],
    "ciLatitude": 39,
    "ciLongitude": 35,
    "ciCapital": "Ankara",
    "capitalLatitude": 39.920777,
    "capitalLongitude": 32.854067,
    "ciBorders": [
        "ARM",
        "AZE",
        "BGR",
        "GEO",
        "GRC",
        "IRN",
        "IRQ",
        "SYR"
    ],
    "provinces": [
        "Adana",
        "Adiyaman",
        "Afyon",
        "Agri",
        "Aksaray",
        "Amasya",
        "Ankara",
        "Antalya",
        "Ardahan",
        "Artvin",
        "Aydin",
        "Balikesir",
        "Bartin",
        "Batman",
        "Bayburt",
        "Bilecik",
        "Bingol",
        "Bitlis",
        "Bolu",
        "Burdur",
        "Bursa",
        "Canakkale",
        "Cankiri",
        "Corum",
        "Denizli",
        "Diyarbakir",
        "Duzce",
        "Edirne",
        "Elazig",
        "Erzincan",
        "Erzurum",
        "Eskisehir",
        "Gaziantep",
        "Giresun",
        "Gumushane",
        "Hakkari",
        "Hatay",
        "Icel",
        "Igdir",
        "Isparta",
        "Istanbul",
        "Izmir",
        "Kahramanmaras",
        "Karabuk",
        "Karaman",
        "Kars",
        "Kastamonu",
        "Kayseri",
        "Kilis",
        "Kirikkale",
        "Kirklareli",
        "Kirsehir",
        "Kocaeli",
        "Konya",
        "Kutahya",
        "Malatya",
        "Manisa",
        "Mardin",
        "Mugla",
        "Mus",
        "Nevsehir",
        "Nigde",
        "Ordu",
        "Osmaniye",
        "Rize",
        "Sakarya",
        "Samsun",
        "Sanliurfa",
        "Siirt",
        "Sinop",
        "Sirnak",
        "Sivas",
        "Tekirdag",
        "Tokat",
        "Trabzon",
        "Tunceli",
        "Usak",
        "Van",
        "Yalova",
        "Yozgat",
        "Zonguldak"
    ],
    "demonym": "Turkish",
    "ciRegion": "Asia",
    "subregion": "Western Asia",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 5,
        "fields_already_populated": 39,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 88.64,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "TUR",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:33.132248",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:33.137248"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "TUR"

def get_country_name():
    """Get the country name."""
    return TUR_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return TUR_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in TUR_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(TUR_meta_data)
    topics = get_all_topics()
    retrieval_meta = TUR_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - TUR - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
