# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - SSD
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:32
# Country: SSD
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:32",
    "country_code": "SSD",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR SSD
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for SSD.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.SSD.SSD_meta_data import SSD_meta_data
#   
#   country_name = SSD_meta_data['name']
#   gdp_data = SSD_meta_data.get('wb_gdp_capita', {})
#   population = SSD_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

SSD_meta_data = {
    "iso3Code": "SSD",
    "iso2Code": "SS",
    "name": "South Sudan",
    "region": "Sub-Saharan Africa",
    "adminregion": "Sub-Saharan Africa (excluding high income)",
    "incomeLevel": "Low income",
    "lendingType": "IDA",
    "capitalCity": "Juba",
    "longitude": 31.6,
    "latitude": 4.85,
    "countryName": "South Sudan",
    "officialStateName": "The Republic of South Sudan",
    "sovereignty": "UN member state",
    "alpha2Code": "SS",
    "alpha3Code": "SSD",
    "numericCode": "728",
    "subdivisionCode": "ISO 3166-2:SS",
    "ccTLD": ".ss",
    "internetCode": ".ss",
    "population": 10913164,
    "surfaceArea": 646883,
    "landArea": 631930,
    "neighbors": [
        "SDN",
        "ETH",
        "KEN",
        "UGA",
        "COD"
    ],
    "SSD": {
        "currencyName": "South Sudanese Pound",
        "currencySymbol": "£",
        "currencyCode": "SSP"
    },
    "officialLanguages": [
        "English"
    ],
    "gdp": 0.0,
    "gdpPerCapita": 0.0,
    "gdpPpp": 0.0,
    "gdpPppPerCapita": 0.0,
    "ciCountryName": "south sudan",
    "ciIso2Code": "SS",
    "callingCodes": [
        "211"
    ],
    "ciCurrencies": [
        "SSP"
    ],
    "ciLanguages": [
        "en"
    ],
    "timezones": [
        "UTC+03:00"
    ],
    "tld": [
        ".ss"
    ],
    "ciLatlng": [
        7,
        30
    ],
    "ciLatitude": 7,
    "ciLongitude": 30,
    "ciCapital": "Juba",
    "capitalLatitude": 4.847202,
    "capitalLongitude": 31.595166,
    "ciBorders": [
        "CAF",
        "COD",
        "ETH",
        "KEN",
        "SDN",
        "UGA"
    ],
    "provinces": [
        "Andalucia",
        "Aragon",
        "Asturias",
        "Baleares (Balearic Islands)",
        "Canarias (Canary Islands)",
        "Cantabria",
        "Castilla y Leon",
        "Castilla-La Mancha",
        "Cataluna",
        "Ceuta",
        "Communidad Valencian",
        "Extremadura",
        "Galicia",
        "Islas Chafarinas",
        "La Rioja",
        "Madrid",
        "Melilla",
        "Murcia",
        "Navarra",
        "Pais Vasco (Basque Country)",
        "Penon de Alhucemas",
        "Penon de Velez de la Gomera"
    ],
    "demonym": "South Sudanese",
    "ciRegion": "Africa",
    "subregion": "Middle Africa",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 9,
        "fields_already_populated": 35,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 79.55,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "SSD",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:32.638214",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:32.642214"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "SSD"

def get_country_name():
    """Get the country name."""
    return SSD_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return SSD_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in SSD_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(SSD_meta_data)
    topics = get_all_topics()
    retrieval_meta = SSD_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - SSD - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
