# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - EST
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:29
# Country: EST
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:29",
    "country_code": "EST",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR EST
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for EST.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.EST.EST_meta_data import EST_meta_data
#   
#   country_name = EST_meta_data['name']
#   gdp_data = EST_meta_data.get('wb_gdp_capita', {})
#   population = EST_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

EST_meta_data = {
    "iso3Code": "EST",
    "iso2Code": "EE",
    "name": "Estonia",
    "region": "Europe & Central Asia",
    "adminregion": "",
    "incomeLevel": "High income",
    "lendingType": "Not classified",
    "capitalCity": "Tallinn",
    "longitude": 24.7586,
    "latitude": 59.4392,
    "countryName": "Estonia",
    "officialStateName": "The Republic of Estonia",
    "sovereignty": "UN member state",
    "alpha2Code": "EE",
    "alpha3Code": "EST",
    "numericCode": "233",
    "subdivisionCode": "ISO 3166-2:EE",
    "ccTLD": ".ee",
    "internetCode": ".ee",
    "population": 1344768,
    "surfaceArea": 45340,
    "landArea": 42750,
    "neighbors": [
        "LVA",
        "RUS"
    ],
    "EST": {
        "currencyCode": "EUR",
        "currencyName": "Euro",
        "currencySymbol": "€"
    },
    "officialLanguages": [
        "Estonian"
    ],
    "gdp": 38100812958.5196,
    "gdpPerCapita": 28332.6290917984,
    "gdpPpp": 62797115057.5185,
    "gdpPppPerCapita": 46697.3597360426,
    "ciCountryName": "estonia",
    "ciIso2Code": "EE",
    "callingCodes": [
        "372"
    ],
    "ciCurrencies": [
        "EUR"
    ],
    "ciLanguages": [
        "et"
    ],
    "timezones": [
        "UTC+02:00"
    ],
    "tld": [
        ".ee"
    ],
    "ciLatlng": [
        59,
        26
    ],
    "ciLatitude": 59,
    "ciLongitude": 26,
    "ciCapital": "Tallinn",
    "capitalLatitude": 59.437216,
    "capitalLongitude": 24.745369,
    "ciBorders": [
        "LVA",
        "RUS"
    ],
    "provinces": [
        "Harjumaa (Tallinn)",
        "Hiiumaa (Kardla)",
        "Ida-Virumaa (Johvi)",
        "Jarvamaa (Paide)",
        "Jogevamaa (Jogeva)",
        "Laane-Virumaa (Rakvere)",
        "Laanemaa (Haapsalu)",
        "Parnumaa (Parnu)",
        "Polvamaa (Polva)",
        "Raplamaa (Rapla)",
        "Saaremaa (Kuessaare)",
        "Tartumaa (Tartu)",
        "Valgamaa (Valga)",
        "Viljandimaa (Viljandi)",
        "Vorumaa (Voru)"
    ],
    "demonym": "Estonian",
    "ciRegion": "Europe",
    "subregion": "Northern Europe",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 5,
        "fields_already_populated": 39,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 88.64,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "EST",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:29.392683",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:29.397682"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "EST"

def get_country_name():
    """Get the country name."""
    return EST_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return EST_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in EST_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(EST_meta_data)
    topics = get_all_topics()
    retrieval_meta = EST_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - EST - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
