# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - MWI
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:31
# Country: MWI
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:31",
    "country_code": "MWI",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR MWI
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for MWI.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.MWI.MWI_meta_data import MWI_meta_data
#   
#   country_name = MWI_meta_data['name']
#   gdp_data = MWI_meta_data.get('wb_gdp_capita', {})
#   population = MWI_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

MWI_meta_data = {
    "iso3Code": "MWI",
    "iso2Code": "MW",
    "name": "Malawi",
    "region": "Sub-Saharan Africa",
    "adminregion": "Sub-Saharan Africa (excluding high income)",
    "incomeLevel": "Low income",
    "lendingType": "IDA",
    "capitalCity": "Lilongwe",
    "longitude": 33.7703,
    "latitude": -13.9899,
    "countryName": "Malawi",
    "officialStateName": "The Republic of Malawi",
    "sovereignty": "UN member state",
    "alpha2Code": "MW",
    "alpha3Code": "MWI",
    "numericCode": "454",
    "subdivisionCode": "ISO 3166-2:MW",
    "ccTLD": ".mw",
    "internetCode": ".mw",
    "population": 20405317,
    "surfaceArea": 118480,
    "landArea": 94280,
    "neighbors": [
        "MOZ",
        "ZMB",
        "TZA"
    ],
    "MWI": {
        "currencyName": "Malawian kwacha",
        "currencySymbol": "MK",
        "currencyCode": "MWK"
    },
    "officialLanguages": [
        "English",
        "Chichewa"
    ],
    "gdp": 13164667626.9363,
    "gdpPerCapita": 645.158692067185,
    "gdpPpp": 35342628209.565,
    "gdpPppPerCapita": 1732.03034334458,
    "ciCountryName": "malawi",
    "ciIso2Code": "MW",
    "callingCodes": [
        "265"
    ],
    "ciCurrencies": [
        "MWK"
    ],
    "ciLanguages": [
        "en",
        "ny"
    ],
    "timezones": [
        "UTC+02:00"
    ],
    "tld": [
        ".mw"
    ],
    "ciLatlng": [
        -13.5,
        34
    ],
    "ciLatitude": -13.5,
    "ciLongitude": 34,
    "ciCapital": "Lilongwe",
    "capitalLatitude": -13.987511,
    "capitalLongitude": 33.768144,
    "ciBorders": [
        "MOZ",
        "TZA",
        "ZMB"
    ],
    "provinces": [
        "Balaka",
        "Blantyre",
        "Chikwawa",
        "Chiradzulu",
        "Chitipa",
        "Dedza",
        "Dowa",
        "Karonga",
        "Kasungu",
        "Likoma",
        "Lilongwe",
        "Machinga (Kasupe)",
        "Mangochi",
        "Mchinji",
        "Mulanje",
        "Mwanza",
        "Mzimba",
        "Nkhata Bay",
        "Nkhotakota",
        "Nsanje",
        "Ntcheu",
        "Ntchisi",
        "Phalombe",
        "Rumphi",
        "Salima",
        "Thyolo",
        "Zomba"
    ],
    "demonym": "Malawian",
    "ciRegion": "Africa",
    "subregion": "Eastern Africa",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 5,
        "fields_already_populated": 39,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 88.64,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "MWI",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:31.504162",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:31.508164"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "MWI"

def get_country_name():
    """Get the country name."""
    return MWI_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return MWI_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in MWI_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(MWI_meta_data)
    topics = get_all_topics()
    retrieval_meta = MWI_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - MWI - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
