# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - TZA
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:33
# Country: TZA
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:33",
    "country_code": "TZA",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR TZA
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for TZA.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.TZA.TZA_meta_data import TZA_meta_data
#   
#   country_name = TZA_meta_data['name']
#   gdp_data = TZA_meta_data.get('wb_gdp_capita', {})
#   population = TZA_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

TZA_meta_data = {
    "iso3Code": "TZA",
    "iso2Code": "TZ",
    "name": "Tanzania",
    "region": "Sub-Saharan Africa",
    "adminregion": "Sub-Saharan Africa (excluding high income)",
    "incomeLevel": "Lower middle income",
    "lendingType": "IDA",
    "capitalCity": "Dodoma",
    "longitude": 35.7382,
    "latitude": -6.17486,
    "countryName": "Tanzania, the United Republic of",
    "officialStateName": "The United Republic of Tanzania",
    "sovereignty": "UN member state",
    "alpha2Code": "TZ",
    "alpha3Code": "TZA",
    "numericCode": "834",
    "subdivisionCode": "ISO 3166-2:TZ",
    "ccTLD": ".tz",
    "internetCode": ".tz",
    "population": 65497748,
    "surfaceArea": 947300,
    "landArea": 885800,
    "neighbors": [
        "KEN",
        "UGA",
        "RWA",
        "BDI",
        "COD",
        "ZMB",
        "MWI",
        "MOZ"
    ],
    "TZA": {
        "currencyName": "Tanzanian shilling",
        "currencySymbol": "Sh",
        "currencyCode": "TZS"
    },
    "officialLanguages": [
        "Swahili",
        "English"
    ],
    "gdp": 75709289056.4457,
    "gdpPerCapita": 1192.40380859375,
    "gdpPpp": 196630460372.992,
    "gdpPppPerCapita": 3096.88452148438,
    "ciCountryName": "tanzania",
    "ciIso2Code": "TZ",
    "callingCodes": [
        "255"
    ],
    "ciCurrencies": [
        "TZS"
    ],
    "ciLanguages": [
        "sw",
        "en"
    ],
    "timezones": [
        "UTC+03:00"
    ],
    "tld": [
        ".tz"
    ],
    "ciLatlng": [
        -6,
        35
    ],
    "ciLatitude": -6,
    "ciLongitude": 35,
    "ciCapital": "Dodoma",
    "capitalLatitude": -6.337282,
    "capitalLongitude": 35.737177,
    "ciBorders": [
        "BDI",
        "COD",
        "KEN",
        "MWI",
        "MOZ",
        "RWA",
        "UGA",
        "ZMB"
    ],
    "provinces": [
        "Arusha",
        "Dar es Salaam",
        "Dodoma",
        "Iringa",
        "Kagera",
        "Kigoma",
        "Kilimanjaro",
        "Lindi",
        "Mara",
        "Mbeya",
        "Morogoro",
        "Mtwara",
        "Mwanza",
        "Pemba North",
        "Pemba South",
        "Pwani",
        "Rukwa",
        "Ruvuma",
        "Shinyanga",
        "Singida",
        "Tabora",
        "Tanga",
        "Zanzibar Central/South",
        "Zanzibar North",
        "Zanzibar Urban/West"
    ],
    "demonym": "Tanzanian",
    "ciRegion": "Africa",
    "subregion": "Eastern Africa",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 5,
        "fields_already_populated": 39,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 88.64,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "TZA",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:33.206075",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:33.209073"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "TZA"

def get_country_name():
    """Get the country name."""
    return TZA_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return TZA_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in TZA_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(TZA_meta_data)
    topics = get_all_topics()
    retrieval_meta = TZA_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - TZA - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
