# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - ATG
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:28
# Country: ATG
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:28",
    "country_code": "ATG",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR ATG
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for ATG.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.ATG.ATG_meta_data import ATG_meta_data
#   
#   country_name = ATG_meta_data['name']
#   gdp_data = ATG_meta_data.get('wb_gdp_capita', {})
#   population = ATG_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

ATG_meta_data = {
    "iso3Code": "ATG",
    "iso2Code": "AG",
    "name": "Antigua and Barbuda",
    "region": "Latin America & Caribbean",
    "adminregion": "",
    "incomeLevel": "High income",
    "lendingType": "IBRD",
    "capitalCity": "Saint John's",
    "longitude": -61.8456,
    "latitude": 17.1175,
    "countryName": "Antigua and Barbuda",
    "officialStateName": "Antigua and Barbuda",
    "sovereignty": "UN member state",
    "alpha2Code": "AG",
    "alpha3Code": "ATG",
    "numericCode": "28",
    "subdivisionCode": "ISO 3166-2:AG",
    "ccTLD": ".ag",
    "internetCode": ".ag",
    "population": 93763,
    "surfaceArea": 440,
    "landArea": 440,
    "neighbors": [],
    "ATG": {
        "currencyCode": "XCD",
        "currencyName": "East Caribbean Dollar",
        "currencySymbol": "$"
    },
    "officialLanguages": [
        "English"
    ],
    "gdp": 1757603703.7037,
    "gdpPerCapita": 18745.1735087796,
    "gdpPpp": 2375639619.9726,
    "gdpPppPerCapita": 25336.6425986007,
    "ciCountryName": "antigua and barbuda",
    "ciIso2Code": "AG",
    "callingCodes": [
        "1268"
    ],
    "ciCurrencies": [
        "XCD"
    ],
    "ciLanguages": [
        "en"
    ],
    "timezones": [
        "UTC−04:00"
    ],
    "tld": [
        ".ag"
    ],
    "ciLatlng": [
        17.05,
        -61.8
    ],
    "ciLatitude": 17.05,
    "ciLongitude": -61.8,
    "ciCapital": "Saint John's",
    "capitalLatitude": 47.561701,
    "capitalLongitude": -52.715149,
    "ciBorders": [],
    "provinces": [
        "Barbuda",
        "Redonda",
        "Saint George",
        "Saint John",
        "Saint Mary",
        "Saint Paul",
        "Saint Peter",
        "Saint Philip"
    ],
    "demonym": "Antiguan,Barbudan",
    "ciRegion": "Americas",
    "subregion": "Caribbean",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 5,
        "fields_already_populated": 39,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 88.64,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "ATG",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:28.022653",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:28.028656"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "ATG"

def get_country_name():
    """Get the country name."""
    return ATG_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return ATG_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in ATG_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(ATG_meta_data)
    topics = get_all_topics()
    retrieval_meta = ATG_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - ATG - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
