# ────────────────────────────────────────────────────────────────────────────────────────────
# Enhanced Country Meta Data - NZL
# ────────────────────────────────────────────────────────────────────────────────────────────
# Auto-generated by: b_download_single_enhanced_country_meta.py
# Generated on: 2025-08-08 18:20:31
# Country: NZL
# Topics updated: 0/0
# ────────────────────────────────────────────────────────────────────────────────────────────

# GENERATION METADATA
# ────────────────────────────────────────────────────────────────────────────────────────────
generation_metadata = {
    "generated_at": "2025-08-08 18:20:31",
    "country_code": "NZL",
    "topics_updated": 0,
    "topics_requested": 0,
    "topic_update_mode": "all",
    "enhanced_data_included": True,
    "generator_script": "b_download_single_enhanced_country_meta.py",
    "data_source": "Impact Titan Enhanced Country Meta System"
}

# ENHANCED COUNTRY META DATA FOR NZL
# ────────────────────────────────────────────────────────────────────────────────────────────
# This dictionary contains comprehensive enhanced metadata for NZL.
# Includes base country information plus recent indicator data for all topics.
# 
# Usage:
#   from impact_titan.impact_3_data.h_saved_world_system.countries.a_impact_country_meta.Original.NZL.NZL_meta_data import NZL_meta_data
#   
#   country_name = NZL_meta_data['name']
#   gdp_data = NZL_meta_data.get('wb_gdp_capita', {})
#   population = NZL_meta_data.get('wb_total_pop', {})
# ────────────────────────────────────────────────────────────────────────────────────────────

NZL_meta_data = {
    "iso3Code": "NZL",
    "iso2Code": "NZ",
    "name": "New Zealand",
    "region": "East Asia & Pacific",
    "adminregion": "",
    "incomeLevel": "High income",
    "lendingType": "Not classified",
    "capitalCity": "Wellington",
    "longitude": 174.776,
    "latitude": -41.2865,
    "countryName": "New Zealand",
    "officialStateName": "New Zealand",
    "sovereignty": "UN member state",
    "alpha2Code": "NZ",
    "alpha3Code": "NZL",
    "numericCode": "554",
    "subdivisionCode": "ISO 3166-2:NZ",
    "ccTLD": ".nz",
    "internetCode": ".nz",
    "population": 5124100,
    "surfaceArea": 267710,
    "landArea": 263310,
    "neighbors": [],
    "NZL": {
        "currencyName": "New Zealand Dollar",
        "currencySymbol": "$",
        "currencyCode": "NZD"
    },
    "officialLanguages": [
        "English",
        "Māori"
    ],
    "gdp": 247234053739.267,
    "gdpPerCapita": 48249.2640150011,
    "gdpPpp": 266283400534.713,
    "gdpPppPerCapita": 51966.8625777626,
    "ciCountryName": "new zealand",
    "ciIso2Code": "NZ",
    "callingCodes": [
        "64"
    ],
    "ciCurrencies": [
        "NZD"
    ],
    "ciLanguages": [
        "en",
        "mi"
    ],
    "timezones": [
        "UTC−11:00",
        "UTC−10:00",
        "UTC+12:00",
        "UTC+12:45",
        "UTC+13:00"
    ],
    "tld": [
        ".nz"
    ],
    "ciLatlng": [
        -41,
        174
    ],
    "ciLatitude": -41,
    "ciLongitude": 174,
    "ciCapital": "Wellington",
    "capitalLatitude": -41.288795,
    "capitalLongitude": 174.777211,
    "ciBorders": [],
    "provinces": [
        "Akaroa",
        "Amuri",
        "Ashburton",
        "Bay of Islands",
        "Bruce",
        "Buller",
        "Chatham Islands",
        "Cheviot",
        "Clifton",
        "Clutha",
        "Cook",
        "Dannevirke",
        "Egmont",
        "Eketahuna",
        "Ellesmere",
        "Eltham",
        "Eyre",
        "Featherston",
        "Franklin",
        "Golden Bay",
        "Great Barrier Island",
        "Grey",
        "Hauraki Plains",
        "Hawera",
        "Hawke's Bay",
        "Heathcote",
        "Hikurangi",
        "Hobson",
        "Hokianga",
        "Horowhenua",
        "Hurunui",
        "Hutt",
        "Inangahua",
        "Inglewood",
        "Kaikoura",
        "Kairanga",
        "Kiwitea",
        "Lake",
        "Mackenzie",
        "Malvern",
        "Manaia",
        "Manawatu",
        "Mangonui",
        "Maniototo",
        "Marlborough",
        "Masterton",
        "Matamata",
        "Mount Herbert",
        "Ohinemuri",
        "Opotiki",
        "Oroua",
        "Otamatea",
        "Otorohanga",
        "Oxford",
        "Pahiatua",
        "Paparua",
        "Patea",
        "Piako",
        "Pohangina",
        "Raglan",
        "Rangiora",
        "Rangitikei",
        "Rodney",
        "Rotorua",
        "Runanga",
        "Saint Kilda",
        "Silverpeaks",
        "Southland",
        "Stewart Island",
        "Stratford",
        "Strathallan",
        "Taranaki",
        "Taumarunui",
        "Taupo",
        "Tauranga",
        "Thames-Coromandel",
        "Tuapeka",
        "Vincent",
        "Waiapu",
        "Waiheke",
        "Waihemo",
        "Waikato",
        "Waikohu",
        "Waimairi",
        "Waimarino",
        "Waimate",
        "Waimate West",
        "Waimea",
        "Waipa",
        "Waipawa",
        "Waipukurau",
        "Wairarapa South",
        "Wairewa",
        "Wairoa",
        "Waitaki",
        "Waitomo",
        "Waitotara",
        "Wallace",
        "Wanganui",
        "Waverley",
        "Westland",
        "Whakatane",
        "Whangarei",
        "Whangaroa",
        "Woodville"
    ],
    "demonym": "New Zealander",
    "ciRegion": "Oceania",
    "subregion": "Australia and New Zealand",
    "currencies": [],
    "currencyCode": "",
    "currencyName": "",
    "currencySymbol": "",
    "_retrieval_metadata": {
        "default_values_applied": 5,
        "fields_already_populated": 39,
        "extracted_fields_total": 44,
        "data_completeness_percentage": 88.64,
        "comprehensive_defaults_available": 424,
        "note": "Only applying defaults to fields with explicit extraction logic",
        "country_code": "NZL",
        "sources_attempted": 13,
        "sources_merged": 12,
        "failed_sources": [],
        "enhanced_data_included": True,
        "defaults_applied": True,
        "retrieval_timestamp": "2025-08-08T18:20:31.809701",
        "topic_update_mode": "all",
        "topics_requested": 0,
        "topics_updated": 0,
        "topics_failed": 0,
        "failed_topics": [],
        "skip_failed_topics": True,
        "is_country": True,
        "is_region": False,
        "enhancement_timestamp": "2025-08-08T18:20:31.812684"
    }
}

# ────────────────────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ────────────────────────────────────────────────────────────────────────────────────────────

def get_country_code():
    """Get the ISO3 country code for this data."""
    return "NZL"

def get_country_name():
    """Get the country name."""
    return NZL_meta_data.get('name', 'Unknown')

def get_generation_info():
    """Get information about when and how this data was generated."""
    return generation_metadata

def get_topic_data(topic_key):
    """Get data for a specific topic/indicator."""
    return NZL_meta_data.get(topic_key, {})

def get_all_topics():
    """Get a list of all available topic keys in this dataset."""
    return [key for key in NZL_meta_data.keys() if key.startswith(('wb_', 'custom_', 'country_', 'region_'))]

def get_recent_change(topic_key):
    """Get recent change information for a specific topic."""
    topic_data = get_topic_data(topic_key)
    if 'changeRate' in topic_data and 'rateDirection' in topic_data:
        return {
            'change_rate': topic_data['changeRate'],
            'direction': topic_data['rateDirection'],
            'absolute_change': topic_data.get('abs_change', 0),
            'current_value': topic_data.get('firstData', 0),
            'previous_value': topic_data.get('secondData', 0),
            'current_date': topic_data.get('firstDate', ''),
            'previous_date': topic_data.get('secondDate', '')
        }
    return None

def validate_data_completeness():
    """Validate the completeness of this country's data."""
    total_fields = len(NZL_meta_data)
    topics = get_all_topics()
    retrieval_meta = NZL_meta_data.get('_retrieval_metadata', {})
    
    return {
        'total_fields': total_fields,
        'total_topics': len(topics),
        'topics_updated': retrieval_meta.get('topics_updated', 0),
        'topics_requested': retrieval_meta.get('topics_requested', 0),
        'completeness_ratio': retrieval_meta.get('topics_updated', 0) / max(retrieval_meta.get('topics_requested', 1), 1)
    }

# ────────────────────────────────────────────────────────────────────────────────────────────
# VALIDATION AND TESTING
# ────────────────────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    print("═" * 80)
    print(f"ENHANCED COUNTRY META DATA - NZL - VALIDATION")
    print("═" * 80)
    
    print(f"Country: {get_country_name()} ({get_country_code()})")
    print(f"Generation info: {get_generation_info()}")
    
    # Test topic functionality
    topics = get_all_topics()
    print(f"Available topics: {len(topics)}")
    
    # Show sample topics with recent changes
    sample_topics = topics[:5] if topics else []
    print(f"Sample topics with recent changes:")
    for topic in sample_topics:
        change_info = get_recent_change(topic)
        if change_info:
            print(f"  {topic}: {change_info['change_rate']:.2%} ({change_info['direction']})")
        else:
            print(f"  {topic}: No change data available")
    
    # Validate data completeness
    completeness = validate_data_completeness()
    print(f"\nData completeness: {completeness['completeness_ratio']:.2%}")
    print(f"Topics updated: {completeness['topics_updated']}/{completeness['topics_requested']}")
    
    print("\n✅ Enhanced country data validation completed!")
